### ISSUE TITLE
JDBCWrapper sets incorrect client info

### ISSUE THREAD

**Issue by sprinterRu** [snowflakedb/spark-snowflake#119]
In `getConnector` method there are these lines:

`conn.setClientInfo("spark-version", SPARK_VERSION)`
`conn.setClientInfo("spark-snowflakedb-version", Utils.VERSION)`

But jdbc driver supports only application name as a parameter to set: https://github.com/snowflakedb/snowflake-jdbc/blob/master/src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java#L785

**Comment by blohr-hs** [comment]
+1. We're having the same issue when the latest versions of both the JDBC driver and the Spark connector.

**Comment by binglihub** [comment]
fixed in 7f170c7532dc4b4ec169c950a2a810b8d441621d
