### ISSUE TITLE
table creation fails if column name is a keyword

### ISSUE THREAD

**Issue by jhuangtw-dev** [snowflakedb/spark-snowflake#12]
calling `dataframe.write()` to a table that does not exist yet results in:
```
CREATE TABLE IF NOT EXISTS test_schema.test_table (id INTEGER NOT NULL, created_at TIMESTAMP, updated_at TIMESTAMP, name STRING NOT NULL, order INTEGER)
```
which fails with: 
```
SQL compilation error: syntax error line 1 at position 138 unexpected ''order''.
```

whereas:
```
CREATE TABLE IF NOT EXISTS test_schema.test_table (id INTEGER NOT NULL, created_at TIMESTAMP, updated_at TIMESTAMP, name STRING NOT NULL, "order" INTEGER)
```
succeeds.

would it make sense to always double-quote the column names during that SQL statement construction?

**Comment by etduwx** [comment]
Thanks, @jhuangtw-dev . Will accept a PR on this; otherwise, I will fix it at my next opportunity.

**Comment by mckim0928** [comment]
Hi @etduwx, I was hopping to take a stab at this PR, just started looking inside the codebase, and was wondering if you could point me in the right direction to get the fix in.

**Comment by mckim0928** [comment]
@etduwx, created a PR with my fix, but having a little issue with setting up my travis credential. Would really appreciate your guidance!

**Comment by etduwx** [comment]
Thanks @mckim0928 ! I've merged your PR and it will be included in our next release, which I am hoping will be very soon. @jhuangtw-dev , when the new version comes out, please reopen an issue if it is still not resolved.
