### ISSUE TITLE
ERROR SnowflakeStrategy: Pushdown failed :null

### ISSUE THREAD

**Issue by MrTomerLevi** [snowflakedb/spark-snowflake#120]
We're getting this error when spark plan is large.
This message is thrown in: https://github.com/snowflakedb/spark-snowflake/blob/master/src/main/scala/net/snowflake/spark/snowflake/pushdowns/SnowflakeStrategy.scala line 30.
Perhaps `planToJson(plan).foreach(addLog(_, System.currentTimeMillis()))` cannot parse the plan into json

**Comment by binglihub** [comment]
fixed in f9e565c33963f804044b3a0f82f97d95dd007dff
