### ISSUE TITLE
error: Symbol 'term net.snowflake.client' is missing from the classpath

### ISSUE THREAD

**Issue by VantageKR** [snowflakedb/spark-snowflake#133]
Hi. When following the recommendation of importing the value for SNOWFLAKE_SOURCE_NAME:

```scala
import net.snowflake.spark.snowflake.Utils.SNOWFLAKE_SOURCE_NAME
```

the following error is thrown due to a dependency on a class not found:

```
error: Symbol 'term net.snowflake.client' is missing from the classpath. This symbol is required by 'value net.snowflake.spark.snowflake.Utils.s3Client'.
```

Removing the problematic import, and replacing it with:

```scala
val SNOWFLAKE_SOURCE_NAME = "net.snowflake.spark.snowflake"
```

solves the issue. What package needs to be included additionally on the classpath to allow the import to succeed please?

Note that this is all in the `spark-shell`, with the latest JDBC driver, along with the latest and most appropriate connector matching the Spark and Scala versions.

**Comment by binglihub** [comment]
I can't reproduce this issue. Could you show me the command you launched the spark-shell with JDBC and Connector?

**Comment by keyouk** [comment]
@VantageKR This happened to me us when downloading spark2.12-2.5.1 

Can you try spark 2.11-2.5.1. This is because the ```spark-shell``` uses scala 2.11.12

**Comment by binglihub** [comment]
@keyouk Spark 2.4 support both Scala 2.11 and Scala 2.12. It depends on the spark config.
