### ISSUE TITLE
Cross Database Joins

### ISSUE THREAD

**Issue by markosl** [snowflakedb/spark-snowflake#162]
Currently, cross database joins are not pushed down due to the following snippet in SnowflakeQuery

  /** Triplet that defines the Snowflake cluster that houses this base relation.
    * Currently an exact match on cluster is needed for a join, but we may not need
    * to be this strict.
    */
  val cluster = (relation.params.sfURL,
    relation.params.sfWarehouse,
    relation.params.sfDatabase)

My team and I have a use case where we require cross database joins to be pushed down so I removed the sfDatabase reference and tested with a local build. It seems to work so far but are there any downsides to expect? 

It would be good to know the exact reason for the restriction in the first place.

**Comment by sfc-gh-mrui** [comment]
@markosl Filed a feature request for this. https://snowflakecomputing.atlassian.net/browse/SNOW-647182
