### ISSUE TITLE
Slow record downloading

### ISSUE THREAD

**Issue by michellemay** [snowflakedb/spark-snowflake#172]
Hi, I was testing out the connector (2.5.6-spark2.4_scala2.11) and found that it was substantially slower than reading equivalent parquet files.  I did some profiling to find out that appending bytes to an ArrayBuffer inside SFRecordReader is really slow.  I suggest to use a raw byte buffer (large enough to fit most use cases) offload it to a regular ArrayBuffer when full..    Doing that made the job run 2.5x faster.

**Comment by Mingli-Rui** [comment]
This issue is fixed from Spark Connector 2.6.0.
