### ISSUE TITLE
spark-snowflake is not compatible with COPY INTO behavior change

### ISSUE THREAD

**Issue by erikselin** [snowflakedb/spark-snowflake#211]
Change detailed here:

https://support.snowflake.net/s/article/COPY-INTO-location-Command-Output-Changes-Pending?r=6&ui-force-components-controllers-recordGlobalValueProvider.RecordGvp.getRecord=1

Which, as far as I can tell, will break pretty much all recent/semi-recent versions of spark-snowflake since they all have some version of this: https://github.com/snowflakedb/spark-snowflake/blob/755a16d17862c8cc1b401598c222b8de421dcf0e/src/main/scala/net/snowflake/spark/snowflake/io/StageReader.scala#L50

**Comment by sfc-gh-mrui** [comment]
This issue is caused by a server behavior change. It has been rollback. Now, this issue is gone. With spark connector 2.6.0 and later, this issue doesn't happen by default. Internally, spark connector will be enhanced to support both OLD and NEW result format for COPY INTO LOCATION.
