### ISSUE TITLE
Query: How dataframe is created out of Snowflake table?

### ISSUE THREAD

**Issue by rkesh-singh** [snowflakedb/spark-snowflake#219]
Can someone please explain below use-case
1) Read from Snowflake
    How Snowflake table is converted into dataframe? As I can see it is converted into csv files by using COPY command.

**Query Observed while reading data from Snowflake with Snowflake -spark connector.**

select * from (SELECT "PERSONID", "LASTNAME", "FIRSTNAME", "ADDRESS", "CITY" FROM "SALES"."PUBLIC"."PERSONS_SNW" WHERE ( "PERSONS_SNW"."PERSONID" < 3)  ORDER BY "PERSONS_SNW"."PERSONID") where 1 = 0 

create  temporary stage if not exists identifier(spark_connector_unload_stage_AliiT0AIbv) 
//why we use GET here, and where file:///tmp/dummy_location_spark_connector_tmp/ this exist , is //it in spark cluster or snowflake cluster

GET @spark_connector_unload_stage_AliiT0AIbv/ file:///tmp/dummy_location_spark_connector_tmp/

alter session set timezone = 'Asia/Kolkata', 
timestamp_ntz_output_format = 'YYYY-MM-DD HH24:MI:SS.FF3',
timestamp_ltz_output_format = 'TZHTZM YYYY-MM-DD HH24:MI:SS.FF3',
timestamp_tz_output_format = 'TZHTZM YYYY-MM-DD HH24:MI:SS.FF3';

//below command will unload table data to csv file of max size 100mb
COPY INTO '@spark_connector_unload_stage_AliiT0AIbv/YGRowzjKNG/' FROM ( SELECT "LASTNAME", "FIRSTNAME", "PERSONID", "CITY", "ADDRESS" FROM (SELECT "PERSONID", "LASTNAME", "FIRSTNAME", "ADDRESS", "CITY" FROM "SALES"."PUBLIC"."PERSONS_SNW" WHERE ( "PERSONS_SNW"."PERSONID" < 3)  ORDER BY "PERSONS_SNW"."PERSONID") ) 
FILE_FORMAT = (
    TYPE=CSV
    COMPRESSION='gzip'
    FIELD_DELIMITER='|'
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    ESCAPE_UNENCLOSED_FIELD = none
    NULL_IF= ()
  )
   MAX_FILE_SIZE =  10000000

**Comment by maasg** [comment]
Does this mean that the resulting `DataFrame` will contain only one partition if the data is < 10Mb ?

**Comment by sfc-gh-mrui** [comment]
@rkesh-singh @maasg 
From Spark Connector 2.6.0, Spark connector doesn't use COPY UNLOAD any more for reading from snowflake.
The user can configure `partition_size_in_mb` (default is 100) to tune the partition count for the DataFrame.
https://docs.snowflake.com/en/user-guide/spark-connector-use.html

If the query result set is smaller than `partition_size_in_mb`, it could be one partition only.
NOTE: `partition_size_in_mb` is the suggested max value, spark connector internally split the partitions by chunks.
The actual partition size may be better or smaller than it.
