### ISSUE TITLE
Documentation incomplete: "usestagingtable" and "truncateTable" relationshiop not mentioned

### ISSUE THREAD

**Issue by YevIgn** [snowflakedb/spark-snowflake#268]
Hello.

Recently we stumbled on the thing, that it is not enough to simply set `usestagingtable=off` to disable stage creation when we write data to Snowflake.

In reality there is a need to also set `truncateTable=on` in this case, e.g.:

```
df.write() \
      .format(SNOWFLAKE_SOURCE_NAME) \
      .options(**sf_options) \
      .option("dbtable", table) \
      .option("usestagingtable", "off") \
      .mode(SaveMode.Overwrite) \
      .save()
```

See `StageWriter` relevant code line: https://github.com/snowflakedb/spark-snowflake/blob/0efd087ada22c2679ad03a20d35fd051465bf8ba/src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala#L258

Am I missing something? If not, I think the documentation should be adjusted to mention this relationship.

**Comment by sfc-gh-mrui** [comment]
If `usestagingtable=off` and `truncateTable=on`, spark connector is sure not to using staging table.
It may be kind of misleading for `writeToTableWithStagingTable`, it doesn't means it must using staging table,
in some cases, it may not use staging table either.

The main purpose to introduce `writeToTableWithoutStagingTable` is that it will not recreate the target table.
