### ISSUE TITLE
Spark connector wrongly resolve DataFrame schema for table with VARIANT column type as STRING

### ISSUE THREAD

**Issue by y-nosa** [snowflakedb/spark-snowflake#275]
Very easy to reproduce

```
create table raw.etl.tbl (a VARIANT)
spark.read.format("net.snowflake.spark.snowflake")
        .options(basicOptions + ("dbtable" -> "raw.etl.tbl")).load().printSchema
```
gives
```
root
 |-- A: string (nullable = true)
```
expected to return Spark's native **StructType**

**Comment by sfc-gh-ema** [comment]
@y-nosa This is a known limitation of the Spark Connector. There may be an improvement for this coming in the future, but for the time being, VARIANTs will be represented as Strings. Please parse the JSON values if you wish to derive structure from VARIANT values.
