### ISSUE TITLE
How does query work?

### ISSUE THREAD

**Issue by josdotso** [snowflakedb/spark-snowflake#311]
I found a blog post from 2017 that says S3 was required at that time but the S3 requirement would eventually go away.  Is that the case now?

Assuming Spark communicated directly with Snowflake now, is the transfer parallelized in any way?  For example, in a Spark cluster with 5 nodes, how many Spark nodes participate in the download from Snowflake?  Is it single threaded? Is the query sharded in any way?

Thanks

**Comment by YevIgn** [comment]
https://github.com/snowflakedb/spark-snowflake/blob/master/src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala - actually both approaches should be parallelized, the directr one is more perfomant and enabled by default if using modern connector version (around 2.5-2.6 there was a significant rewrite, officially Arrow in-flight format is used since 2.7). Spark-Snowflake honors parallelism setting of Apache Spark (spark.sql.shuffle.partitions) and will map data from table or query to the appropriate number of partitions.

**Comment by YevIgn** [comment]
We use Spark-Snowflake for quite a bit of time, way before copyUnload was superseded by direct result set ingestion and utilization of cluster resources was never an issue (at least in relation to connector).

**Comment by sfc-gh-mrui** [comment]
@YevIgn 
I found a blog post from 2017 that says S3 was required at that time but the S3 requirement would eventually go away. Is that the case now?
```
External S3 is not required now. Currently, SC will use snowflake internal stage when writing DataFrame
to Snowflake. And don't use stage any more when reading from snowflake.
```

Assuming Spark communicated directly with Snowflake now, is the transfer parallelized in any way? For example, in a Spark cluster with 5 nodes, how many Spark nodes participate in the download from Snowflake? Is it single threaded? Is the query sharded in any way?
```
From Spark Connector 2.6.0, Spark connector doesn't use COPY UNLOAD any more for reading from snowflake.
The user can configure `partition_size_in_mb` (default is 100) to tune the partition count for the DataFrame.
https://docs.snowflake.com/en/user-guide/spark-connector-use.html
```

**Comment by arthurli1126** [comment]
@sfc-gh-mrui @sfc-gh-jfan @YevIgn Do you have benchmark to compare the performance between direct vs s3 copy unload? Also, with s3 approach we can configure the vpce for s3 to avoid the traffic go through the internet but wondering if the performance comes with the direct connection worth the cost and latency.

**Comment by bzillins** [comment]
I recently was looking into this and found the following which appears to be written by @sfc-gh-mrui https://www.snowflake.com/blog/snowflake-connector-for-spark-version-2-6-turbocharges-reads-with-apache-arrow/
