### ISSUE TITLE
Snowflake Spark Connector Broken with Snowflake Version 5.12

### ISSUE THREAD

**Issue by matthewglover151** [snowflakedb/spark-snowflake#347]
The snowflake version 5.12 got pushed to our Snowflake account Wednesday 4/12. The Spark Connector does not work with this bundle, as the date_format is put into Timestamp format. 

receiving the following row load errors when trying to load dates in ANSI format:

Date '2021-04-07' is not recognized

From Snowflake Support:

The error thrown is “Date '2021-04-07' is not recognized”.

This appears to be due to the autogenerated COPY INTO query from the connector does not use the correct date format.

Certainly this does look like a serious issue and something that we would like for our Engineering team to start looking at right away.

**Comment by matthewglover151** [comment]
After running this command at the recommendation Snowflake Support: 

select system$disable_behavior_change_bundle('2021_02');

The following autogenerated copy into works just fine:

copy into unittest_schema.AIRFLOWTEMP_YHXFQIXDAI FROM @spark_connector_load_stage_USQYBQHpxZ/IlhvATQoex/ 
FILE_FORMAT = (
    TYPE=CSV
    FIELD_DELIMITER='|'
    NULL_IF=()
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    TIMESTAMP_FORMAT='TZHTZM YYYY-MM-DD HH24:MI:SS.FF3'
    DATE_FORMAT='TZHTZM YYYY-MM-DD HH24:MI:SS.FF3'
    BINARY_FORMAT=BASE64
  )
            ON_ERROR = CONTINUE 

However, if 2021_02 bundle is enabled, we get the Date row errors from above.

**Comment by matthewglover151** [comment]
@sf-gh-icseri @sfc-gh-abhatnagar @sfc-gh-azhan @sfc-gh-bli @sfc-gh-bpeterson 

I'll gladly fix this myself if you guys give me access to create a pull request.

**Comment by sfc-gh-abhatnagar** [comment]
@sfc-gh-mrui can you please have a look and update please .

**Comment by sfc-gh-mrui** [comment]
I am aware of this issue, and I am investigating it. Who is the support engineer on this issue. I may need to confirm some info with him/her.

**Comment by sfc-gh-mrui** [comment]
Hi, @matthewglover151,

I am investigating this issue. Could you confirm whether a security manager is configured for this environment and there is some special setting for property about `snowflake.client.info`? for example,
```
permission java.util.PropertyPermission "snowflake.client.info", "write";
```

**Comment by matthewglover151** [comment]
Our cluster is a Spark Standalone cluster running on Spark 3.0.0. We do not use any special snowflake client properties.:

spark.jars.packages                       net.snowflake:spark-snowflake_2.12:2.8.4-spark_3.0,org.apache.hadoop:hadoop-aws:3.2.0,io.delta:delta-core_2.12:0.7.0,com.amazonaws:aws-java-sdk-bundle:1.11.375,com.springml:spark-sftp_2.11:1.1.5
spark.dynamicAllocation.enabled true
spark.driver.memory 2G
spark.driver.cores 1
spark.executor.cores 1
spark.executor.instances 3
spark.executor.memory 3G
spark.dynamicAllocation.maxExecutors 8
spark.dynamicAllocation.minExecutors 1
spark.shuffle.service.enabled true
spark.driver.memoryOverhead 1G
spark.executor.memoryOverhead 1G
spark.sql.broadcastTimeout 3600

spark.sql.legacy.parquet.datetimeRebaseModeInWrite CORRECTED
spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version 2

spark.worker.cleanup.enabled true
spark.worker.cleanup.interval 1800
spark.worker.cleanup.appDataTtl 3600

spark.authenticate true
spark.authenticate.secret [redacted]
spark.network.crypto.enabled true

spark.driver.defaultJavaOptions -Duser.timezone=UTC -Djava.security.egd=file:///dev/urandom
spark.executor.defaultJavaOptions -Duser.timezone=UTC -Djava.security.egd=file:///dev/urandom

**Comment by sfc-gh-mrui** [comment]
Hi, @matthewglover151,

Thanks for the quick response. These configuration looks good to me. Can you share what's the OS and JVM you are using?

**Comment by matthewglover151** [comment]
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)


PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by sfc-gh-mrui** [comment]
Hi, @matthewglover151,

Thanks for the quick response!
We will continue to investigate this issue.
But could you please confirm whether this issue blocks your production system?
I suppose this issue has been mitigated by setting some parameters.
Is your team OK to keep these parameters setting for some time?

**Comment by matthewglover151** [comment]
This will block our production in about 8 weeks when we are forced to upgrade, but for now we are able to disable the 2021_02 bundle.

**Comment by matthewglover151** [comment]
@sfc-gh-mrui This error is back again. Does the newest version of Spark Snowflake resolve it?

**Comment by sfc-gh-mrui** [comment]
@matthewglover151 Sorry, the latest Spark Snowflake doesn't resolve this problem. I would like the support engineer can give you an update.

**Comment by bmtKIA6** [comment]
Seeing the same error w/ Spark 3.1.2. We are trying to load data into timestamp_ntz columns (LOGTIMEUTC is a timestamp_ntz column)

`2021-06-27 22:54:14 [ERROR] [park.snowflake.io.StageWriter$:429] Error occurred while loading files to Snowflake: net.snowflake.client.jdbc.SnowflakeSQLException: Timestamp '2021-06-27 21:43:20' is not recognized
  File 'MqZNSz6nkl/1.CSV.gz', line 1, character 3693
  Row 1, column "LOG"["LOGTIMEUTC":53]`

**Comment by matthewglover151** [comment]
@bmtKIA6 The 2.9.0 release of Spark-Snowflake connector seems to have fixed this problem for us.

**Comment by bmtKIA6** [comment]
Will test locally with the latest, however our spark runtime is Databricks, and they are still on 2.8.1... (Databricks Runtime 8.3)

**Comment by sfc-gh-mrui** [comment]
@bmtKIA6 DataBricks is still using 2.8.1. Snowflake has notified DataBricks to use latest spark connector 2.9.0.
I think they should use it in newer DB versions.
You can change the DB cluster init script to replace the embedded SC 2.8.1 with 2.9.0.

**Comment by sfc-gh-mrui** [comment]
It has been fixed.
