### ISSUE TITLE
spark-snowflake writing a dataframe ignores option error_on_column_count_mismatch=false

### ISSUE THREAD

**Issue by tchoedak** [snowflakedb/spark-snowflake#35]
## Environment 
- python 2.7
- spark 2.2.0
- snowflake-jdbc-3.4.2.jar
- spark-snowflake_2.11-2.2.8.jar
- emr 5.11.1

## Setup
create snowflake table that has an auto incrementing id column, using file format option error_on_column_count_mismatch=false

```sql
create table my_db.my_schema.test_table (
id integer autoincrement primary key,
user_id integer
)
stage_file_format = (TYPE=PARQUET, ERROR_ON_COLUMN_COUNT_MISMATCH=FALSE);
```

create a dataframe that only has `user_id`

```python
from pyspark.sql import Row

data = [Row(user_id=x) for x in [99, 98, 97]]
df = spark.createDataFrame(data)
spark.write.format('jdbc')...
```

## Issue

Writing a dataframe that has less columns than the destination table raises an `net.snowflake.client.jdbc.SnowflakeSQLException` and suggests `use file format option error_on_column_count_mismatch=false to ignore this error`. When following the suggestion, the same Exception occurs. This operation works on mysql and redshift, but not on snowflake.

#### Expeceted behavior
Assume the setup in ##setup, calling a spark jdbc write on a dataframe with column `user_id` should write the data into the destination table that has columns `id, user_id`, incrementing the autoincrement id column while populating the `user_id` column with data from dataframe. (Confirmed this works using snowflake-sqlalchemy, and snowflake SQL).

Assume a setup where you have columns `user_id, name, zip_code` on a snowflake table and a dataframe with columns `user_id, name`. Calling a spark jdbc write should populate `user_id, name` columns in the destination table, while leaving zip_code NULL. 

#### Temporary workarounds
Although not ideal, we use the following workarounds for both issues so this may be useful for other readers/users.

For behavior 1, we are writing dataframe with column `user_id` into a temporary table that only has `user_id` and then performing a insert from select statement using sqlalchemy.

For behavior 2, we are generating the missing columns in the dataframe using `F.withColumn('zip_code', None`) and then successfully writing the dataframe into the destination table, filling NULL for columns that we were originally missing.

**Comment by brupm** [comment]
👍

**Comment by etduwx** [comment]
Hi @tchoedak ,

We recommend that the column-mapping option be used here. As copied from the release notes:

> - Support for column-mapping. Columns may be written out-of-order, or to an arbitrary set of equal quantity, type-compatible columns from a Dataframe to a Snowflake table. Example:

```
    df.write.format(SNOWFLAKE_SOURCE_NAME).options(connectorOptionsNoTable)
      .option("dbtable", dbtable)
      .option("columnmap", Map("one" -> "sf_col2", "two" -> "sf_col1").toString())
      .mode(SaveMode.Append).save()
```

This should allow a one-to-one mapping of Spark dataframe columns to Snowflake target table columns.

**Comment by Ortizer** [comment]
@etduwx Is there a way to do that automatically without specifying every column in the mapping?  Having a similar issue on a table with 85 columns, the last of which is an autoincrementing key, and it would be preferable not to have to add all the columns to the hive view creation script twice.

Thanks!

**Comment by gnanram** [comment]
For any future solution seekers, "columnmap" option helped me tremenduosly to insert to a table having auto incrementing id. In our case we have a dataframe that has all columns minus auto incrementing id with same exact column names. so used this function to simplify the columnmap. in case of different columns it might need little extra steps.    
```
// Define dataframes columns mapped one to one to snowflake columns for auto increment id to work
val sfColMap = prepResultDF.columns.map(c => c -> c).toMap.toString
```
Then used the above variable in my snowflake spark write option.  
```
// Write dataframes content to DQ validation results table
prepResultDF
  .write
  .format("snowflake")
  .options(sfOptions)
  .option("dbtable", tableName)
  .option("columnmap", sfColMap)
  .mode("append") 
  .save
```

**Comment by szambetti** [comment]
Also for python future reference, i was able to resolve the issue as follows:

`"column_mismatch_behavior" : 'ignore',
                        "column_mapping" : 'name'`

The error message was telling me to use error_on_column_count_mismatch=false but that does not seem to resolve the issue

complete code:

`
sfOptions = {
                       "sfUrl" : f"{account}.snowflakecomputing.com",
                        "sfUser" : user,
                        "pem_private_key" : key,
                        "sfDatabase" : database,
                        "sfSchema" : schema,
                        "sfWarehouse" : warehouse,
                        "sfRole" : role,
                        "truncate_columns" : 'off',
                        "usestagingtable" : 'off'
                        "column_mismatch_behavior" : 'ignore',
                        "column_mapping" : 'name'
                        }

df_test_write_spark.write.format("snowflake").options(**sfOptions).option("dbtable", table).mode("append").save()`
