### ISSUE TITLE
does snowflake spark connector supports spark partitionOverwriteMode

### ISSUE THREAD

**Issue by sameer2800** [snowflakedb/spark-snowflake#362]
I am just wondering does spark connector support spark partition overwrite mode. I have a use case where i have to programmatically insert partitioned  s3 data into snowflake. As far I see in the documentation and datawriter.class , the connector supports append and overwrite mode at table level. But i am looking for a way to overwrite data at table's cluster key level. (i will map my S3 partition with the snowflake cluster key) 
The other alternative i could think of is to fire a delete query with a particular cluster key using JDBC driver  and insert into a table using append. I will be wrapping this piece in a transaction to handle corner cases.
But what I am looking for is a SF native way to support overwrite mode at the partition level.  any help would be appreciated.

**Comment by tmszk** [comment]
We also have this use case so +1

As a work-around we indeed use a DELETE query. No need to make a separate connection with JDBC driver though, you can execute this query through spark-connector using 2 possible methods:
* "preactions"-option when writing: https://docs.snowflake.com/en/user-guide/spark-connector-use.html#executing-ddl-dml-sql-statements
* Utils.runQuery: https://docs.snowflake.com/en/user-guide/spark-connector-use.html#executing-ddl-dml-sql-statements

**Comment by sfc-gh-mrui** [comment]
Spark connector only supports the mode defined in SaveMode. 
```
public enum SaveMode {
  /**
   * Append mode means that when saving a DataFrame to a data source, if data/table already exists,
   * contents of the DataFrame are expected to be appended to existing data.
   *
   * @since 1.3.0
   */
  Append,
  /**
   * Overwrite mode means that when saving a DataFrame to a data source,
   * if data/table already exists, existing data is expected to be overwritten by the contents of
   * the DataFrame.
   *
   * @since 1.3.0
   */
  Overwrite,
  /**
   * ErrorIfExists mode means that when saving a DataFrame to a data source, if data already exists,
   * an exception is expected to be thrown.
   *
   * @since 1.3.0
   */
  ErrorIfExists,
  /**
   * Ignore mode means that when saving a DataFrame to a data source, if data already exists,
   * the save operation is expected to not save the contents of the DataFrame and to not
   * change the existing data.
   *
   * @since 1.3.0
   */
  Ignore
}

```
