### ISSUE TITLE
Spark connector generates incorrect SQL for ORDER BY ... LIMIT N queries

### ISSUE THREAD

**Issue by mallman** [snowflakedb/spark-snowflake#364]
It appears the Spark connector is generating incorrect queries for Spark SQL queries that end with an `ORDER BY ... LIMIT N` clause when pushdown is enabled.

I think the easiest way to break down this issue is by going through one of the integration tests. I believe there are a couple of problems with the integration test at https://github.com/snowflakedb/spark-snowflake/blob/v2.9.0-spark_3.1/src/it/scala/net/snowflake/spark/snowflake/SimpleNewPushdownIntegrationSuite.scala#L139-L161 that make it mask the bug I'm seeing in production. The code for that integration test, as of version 2.9.0, is as follows:

```scala
  test("LIMIT and SORT") {
    val result =
      sparkSession.sql("""
        select * from df2
        where p > 1 AND p < 3 order by p desc limit 1
      """.stripMargin)

    testPushdown(
      s"""SELECT * FROM
                     |	(SELECT * FROM
                     |		(SELECT * FROM
                     |			(SELECT * FROM ($test_table2) AS "sf_connector_query_alias"
                     |		) AS "subquery_0"
                     |	 WHERE ((("subquery_0"."P" IS NOT NULL) AND ("subquery_0"."P" > 1)) AND ("subquery_0"."P" < 3))
                     |	) AS "subquery_1"
                     | ORDER BY ("subquery_1"."P") DESC
                     |) AS "subquery_2"
                     | LIMIT 1
      """.stripMargin,
      result,
      Seq(Row(2, 2))
    )
  }
```

First, I believe the generated query is an incorrect translation of the original query

```sql
select * from df2 where p > 1 AND p < 3 order by p desc limit 1
```

Essentially, the generated query is

```sql
select * from (select * from df2 where p > 1 AND p < 3 order by p desc) limit 1
```

The results of that query are non-deterministic because the inner "order by" is irrelevant to the correctness of the result. That query is semantically the same as

```sql
select * from (select * from df2 where p > 1 AND p < 3) limit 1
```

One way to correct the generated query would be to push the limit clause into the "order by" subquery and eliminate the outermost query, like

```sql
SELECT * FROM
  (SELECT * FROM
    (SELECT * FROM ($test_table2) AS "sf_connector_query_alias") AS "subquery_0"
      WHERE ((("subquery_0"."P" IS NOT NULL) AND ("subquery_0"."P" > 1)) AND ("subquery_0"."P" < 3))) AS "subquery_1"
ORDER BY ("subquery_1"."P") DESC LIMIT 1
```

or, more succinctly,

```sql
select * from (select * from (select * from df2) sq0 where sq0.p > 1 AND sq0.p < 3) sq1
  order by sq1.p desc limit 1
```

Another problem with the test is that, because the result of the generated query is non-deterministic, it's incorrect to assert that the result is `Seq(Row(2, 2))`. The way the `df2` table/relation is defined, `Seq(Row(3,2))` is also an acceptable result for this query. Unfortunately, the non-deterministic nature of this query means that the test is unreliable.

If we agree that this is a bug, I can propose a couple of solutions.

I believe that the following patch will correct the problem:

```
diff --git a/src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala b/src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala
index 23a9375..b861b95 100644
--- a/src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala
+++ b/src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala
@@ -153,10 +153,10 @@ private[querygeneration] class QueryBuilder(plan: LogicalPlan) {
               ProjectQuery(fields, subQuery, alias.next)
             case Aggregate(groups, fields, _) =>
               AggregateQuery(fields, groups, subQuery, alias.next)
-            case Limit(limitExpr, _) =>
-              SortLimitQuery(Some(limitExpr), Seq.empty, subQuery, alias.next)
             case Limit(limitExpr, Sort(orderExpr, true, _)) =>
               SortLimitQuery(Some(limitExpr), orderExpr, subQuery, alias.next)
+            case Limit(limitExpr, _) =>
+              SortLimitQuery(Some(limitExpr), Seq.empty, subQuery, alias.next)
 
             case Sort(orderExpr, true, Limit(limitExpr, _)) =>
               SortLimitQuery(Some(limitExpr), orderExpr, subQuery, alias.next)
```

That being said, I have not been able to run the integration tests or write new ones to validate this potential fix. Further, this patch will result in the generated query to have an unnecessary nested `order by`, like

```sql
select * from (select * from df2 where p > 1 AND p < 3 order by p desc) order by p desc limit 1
```

While this is a correct translation of the original query, it's obviously overcomplicated.

If we want to avoid the nested ordering I believe the following patch will work:

```
diff --git a/src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala b/src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala
index 23a9375..672ab96 100644
--- a/src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala
+++ b/src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala
@@ -153,10 +153,16 @@ private[querygeneration] class QueryBuilder(plan: LogicalPlan) {
               ProjectQuery(fields, subQuery, alias.next)
             case Aggregate(groups, fields, _) =>
               AggregateQuery(fields, groups, subQuery, alias.next)
+
+            case Limit(limitExpr, Sort(orderExpr, true, _)) =>
+              subQuery match {
+                case SortLimitQuery(None, orderBy, child, alias) =>
+                  SortLimitQuery(Some(limitExpr), orderExpr, child, alias)
+                case _ =>
+                  SortLimitQuery(Some(limitExpr), orderExpr, subQuery, alias.next)
+              }
             case Limit(limitExpr, _) =>
               SortLimitQuery(Some(limitExpr), Seq.empty, subQuery, alias.next)
-            case Limit(limitExpr, Sort(orderExpr, true, _)) =>
-              SortLimitQuery(Some(limitExpr), orderExpr, subQuery, alias.next)
 
             case Sort(orderExpr, true, Limit(limitExpr, _)) =>
               SortLimitQuery(Some(limitExpr), orderExpr, subQuery, alias.next)
```

I can submit a PR if you're interested.

Thank you.

**Comment by mallman** [comment]
I just found this, which appears to be relevant:

https://community.snowflake.com/s/article/SELECT-query-with-LIMIT-clause-returns-non-deterministic-result-if-ORDER-BY-clause-exists-in-different-level

**Comment by sfc-gh-mrui** [comment]
@mallman You are appreciated so much for the deep digging for the problem!
Spark Connector pushdown has to analyze the Spark Plan not spark SQL, it may be some different with the spark SQL because it may have been normalized or optimized. So, the pushdown generated query may be more complex than your expectation. We depends Snowflake query processing can do optimization for the query. SC pushdown focuses on correctness.

As for your proposed solution, I vote on the first proposal. It's more like fixing a code typo.
Below `case Limit(limitExpr, Sort(orderExpr, true, _))` is used to handle the special case of SORT + LIMIT, but it is located after  `case Limit(limitExpr, _)`.
So, it is never used. It makes sense to exchange their order.
```
             case Limit(limitExpr, Sort(orderExpr, true, _)) =>
               SortLimitQuery(Some(limitExpr), orderExpr, subQuery, alias.next)
```

If you don't mind, I can take over to submit a PR because we also need to change and add some test case for it.

**Comment by mallman** [comment]
> If you don't mind, I can take over to submit a PR because we also need to change and add some test case for it.

Works for me. Thank you!

**Comment by sfc-gh-mrui** [comment]
@mallman https://github.com/snowflakedb/thundersnow/pull/575 is the PR. Are you good on it?

**Comment by sfc-gh-mrui** [comment]
fixed https://github.com/snowflakedb/spark-snowflake/pull/365
