### ISSUE TITLE
Failed to upgrade spark-snowflake to newest version

### ISSUE THREAD

**Issue by yuzhangyi** [snowflakedb/spark-snowflake#393]
Hi, @sfc-gh-mrui,

Recently we try to upgrade spark-snowflake to be newest version, but it cause thousands of conflicts and impact our product, the details is:
![image](https://user-images.githubusercontent.com/44692931/140505086-a9a3ccd9-3525-414f-86b7-11c85bef29bf.png)

Could you help solve this issue with releasing new version SDK to us? Maybe you can use following approaches:
1. Remove the embed code and keep them as dependency (“com.google”, “javax”, “org.checkerframework” ) reference like before.
2. Use new namespace (for example, _snowflake_.com.google.common.base.xxx, not com.google.common.base.xxx) for each class/java file in the embed code.
![image](https://user-images.githubusercontent.com/44692931/140507421-5db9f9df-969c-4c94-b5d4-772d23e607cd.png)

Thanks!

**Comment by ryanstrat** [comment]
A fix that removes the dependency from the ingest sdk was merged in https://github.com/snowflakedb/snowflake-ingest-java/pull/101, but the Snowflake staff hasn't cut a release of that library since merging the fix.

**Comment by sfc-gh-mrui** [comment]
@yuzhangyi This is a dependency issue from `snowflake-ingest-sdk`. It has been fixed from `1.0.1`. But it is in beta now. Once it is GA, SC will upgrade to use it to avoid the confilct.
https://mvnrepository.com/artifact/net.snowflake/snowflake-ingest-sdk/1.0.0-beta
