### ISSUE TITLE
KnownFloatingPointNormalized not pushed down in 2.10.0 connector version

### ISSUE THREAD

**Issue by YevIgn** [snowflakedb/spark-snowflake#424]
Since we migrated to Spark 3.2.0 and Spark-Snowflake connector 2.10.0 versions, we have observed that one of our joins started failing on pushdown taking significantly more time to complete (i.e. 10 min -> 1h) in logs we see that knownfloatingpointnormalized expression can't be pushed down. As far as it seems this started from the following ticket: https://issues.apache.org/jira/browse/SPARK-29274

For now we rewrote our query to direct SQL and got same performance back. Do you have plans in adding support for this expression in future versions? - https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/constraintExpressions.scala#L55

**Comment by sfc-gh-mrui** [comment]
Filed a feature request to investigate the feature request. https://snowflakecomputing.atlassian.net/browse/SNOW-647165
