### ISSUE TITLE
[Request] Support Spark 3.3

### ISSUE THREAD

**Issue by originou** [snowflakedb/spark-snowflake#435]
Hello,

Is it plan for a support of new release of spark 3.3 ? :)

Thanks

**Comment by o-shevchenko** [comment]
We are waiting for it us well. Is there any update for that?
Thanks!

**Comment by o-shevchenko** [comment]
There is PR to bring Spark 3.3 support: https://github.com/snowflakedb/spark-snowflake/pull/438.

**Comment by roxchkplusony** [comment]
Glad to see the PR merged. Just waiting now for the release :)

**Comment by sfc-gh-ahuck** [comment]
The [newest release](https://mvnrepository.com/artifact/net.snowflake/spark-snowflake_2.13/2.11.1-spark_3.3) is compatible with Spark 3.3. 

So I think this can be closed? @sfc-gh-jfan
