### ISSUE TITLE
Add Support for Ingesting Spark Array data types from a Snowflake Array data type

### ISSUE THREAD

**Issue by rportilla-databricks** [snowflakedb/spark-snowflake#73]
Currently, when a column data type in Snowflake is ARRAY (e.g. result of split), the resulting data type when ingested through Spark cannot be read using an Array data type. The sample code below demonstrates the limitation. The result of reading an ARRAY column is a java.lang.String value which cannot be converted to an Array.

**Error**

SparkException: Job aborted due to stage failure: Task 0 in stage 7.0 failed 4 times, most recent failure: Lost task 0.3 in stage 7.0 (TID 25, 10.0.251.155, executor 2): java.lang.IllegalArgumentException: The value (["127","0","0","1"]) of the type (java.lang.String) cannot be converted to an array of string

**Sample Code to Show Limitation**

import org.apache.spark.sql.types._
import net.snowflake.spark.snowflake.Utils 

Utils.runQuery(options, """CREATE SCHEMA IF NOT EXISTS databricks_demo_array_type""")
Utils.runQuery(options, """DROP TABLE IF EXISTS DD_ARRAY_TEST""")
Utils.runQuery(options, """create table dd_array_test as select split('127.0.0.1', '.') as num_array_x from adult limit 2""")

val customSchema = StructType(Array( 
StructField("num_array_x", ArrayType(StringType, true), true)))
  
val dataset = spark.read.format("snowflake").options(options).schema(customSchema).option("dbtable", "dd_array_test").load()

**Comment by binglihub** [comment]
To load variant types from snowflake to spark. You should provide the schema of table manually. Otherwise, the connector will convert all variant types values to StringType automatically.
For example

```scala
val schema = new StructType(
    Array(
      StructField("ARR", ArrayType(IntegerType), false),
      StructField("OB",StructType(
        Array(
          StructField("str", StringType, false)
        )
      ), false),
      StructField("MAP", MapType(StringType,StringType), false),
      StructField("NUM", IntegerType, false)
    )
  )

val df = sqlContext.read
      .format(SNOWFLAKE_SOURCE_NAME)
      .options(connectorOptionsNoTable)
      .option("dbtable", tableName1)
      .schema(schema)
      .load().collect()
```

**Comment by rportilla-databricks** [comment]
The schema has been provided manually above (customSchema). Isn't this the same?
