### ISSUE TITLE
Savemode.Overwrite Causes a table swap without the temp table gaining initial table properties

### ISSUE THREAD

**Issue by AdrielVelazquez** [snowflakedb/spark-snowflake#75]
Savemode.Overwrite in the background causes a swap on the table causing all clustering information and metadata information to be lost in the process. 

The create statement should be

```CREATE TABLE  IF NOT EXISTS my_unique_table_staging_1054285534 LIKE my_unique_table```

instead of 

```
CREATE TABLE IF NOT EXISTS my_unique_table_staging_1054285534 (user_id INTEGER)
```

Exact Copy Grants and Clustering Keys should be moved as well

**Comment by binglihub** [comment]
Hi @AdrielVelazquez, please try to set "truncate_table = on" in connector option.
